export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILED = "GET_PIZZAS_FAILED";

export const ADD_PIZZA_REQUEST = "ADD_PIZZA_REQUEST";
export const ADD_PIZZA_SUCCESS = "ADD_PIZZA_SUCCESS";
export const ADD_PIZZA_FAILED = "ADD_PIZZA_FAILED";


