export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILED = "GET_PIZZAS_FAILED";

export const GET_PIZZA_ID_REQUEST = "GET_PIZZAS_ID_REQUEST";
export const GET_PIZZA_ID_SUCCESS = "GET_PIZZAS_ID_SUCCESS";
export const GET_PIZZA_ID_FAILED = "GET_PIZZAS_ID_FAILED";

export const ADD_PIZZA_REQUEST = "ADD_PIZZA_REQUEST";
export const ADD_PIZZA_SUCCESS = "ADD_PIZZA_SUCCESS";
export const ADD_PIZZA_FAILED = "ADD_PIZZA_FAILED";

export const EDIT_PIZZA_REQUEST = "EDIT_PIZZA_REQUEST";
export const EDIT_PIZZA_SUCCESS = "EDIT_PIZZA_SUCCESS";
export const EDIT_PIZZA_FAILED = "EDIT_PIZZA_FAILED";


